---
# Database Secrets
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: product-service
  labels:
    app: product-service
spec:
  encryptedData:
    # Values are base64 encoded and encrypted
    # These will be decrypted by the SealedSecrets controller
    POSTGRES_USER: "<encrypted-POSTGRES_USER>"
    POSTGRES_PASSWORD: "<encrypted-POSTGRES_PASSWORD>"
    POSTGRES_DB: "<encrypted-POSTGRES_DB>"
    DATABASE_URL: "<encrypted-DATABASE_URL>"
---
# Application Secrets
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: product-service
  labels:
    app: product-service
spec:
  encryptedData:
    # Application secrets (encrypted)
    JWT_SECRET: "<encrypted-JWT_SECRET>"
    API_KEY: "<encrypted-API_KEY>"
    ENCRYPTION_KEY: "<encrypted-ENCRYPTION_KEY>"
---
# Redis Secrets (if needed)
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: product-service
  labels:
    app: product-service
spec:
  encryptedData:
    REDIS_PASSWORD: "<encrypted-REDIS_PASSWORD>"
---
# External API Secrets
# apiVersion: bitnami.com/v1alpha1
# kind: SealedSecret
# metadata:
#   name: external-api-secret
#   namespace: product-service
#   labels:
#     app: product-service
# spec:
#   encryptedData:
#     AWS_ACCESS_KEY_ID: QVVJQVBBTU1aSEVYQU1QTEU=        # AKIAEXAMPLEKEY
#     AWS_SECRET_ACCESS_KEY: d0phbHJYVXRuRkVNSS9LN01ERU5HL2VYQU1QTEVLRVK=  # wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY