---
# Database Secrets
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: product-service
  labels:
    app: product-service
type: Opaque
data:
  # Values are base64 encoded
  # To encode: echo -n 'your-value' | base64
  # To decode: echo 'encoded-value' | base64 -d
  # Template placeholders only. Replace with values injected by your secret manager.
  POSTGRES_USER: "<base64-POSTGRES_USER-PLACEHOLDER>"
  POSTGRES_PASSWORD: "<base64-POSTGRES_PASSWORD-PLACEHOLDER>"
  POSTGRES_DB: "<base64-POSTGRES_DB-PLACEHOLDER>"
  DATABASE_URL: "<base64-DATABASE_URL-PLACEHOLDER>"
---
# Application Secrets
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: product-service
  labels:
    app: product-service
type: Opaque
data:
  # Application secrets
  JWT_SECRET: "<base64-JWT_SECRET-PLACEHOLDER>"
  API_KEY: "<base64-API_KEY-PLACEHOLDER>"
  ENCRYPTION_KEY: "<base64-ENCRYPTION_KEY-PLACEHOLDER>"
---
# Redis Secrets (if needed)
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: product-service
  labels:
    app: product-service
type: Opaque
data:
  REDIS_PASSWORD: "<base64-REDIS_PASSWORD-PLACEHOLDER>"
---
# External API Secrets (example template)
# Use only as a placeholder/template. Do NOT commit real credentials.
# Example uses the canonical AWS example access key (not real):
#   AKIAIOSFODNN7EXAMPLE (base64: QUtJQUlPU0ZPRE5ONDdFWEFNUExF)
# Replace with your secret manager reference or remove the block entirely.