---
# ArgoCD Application for Product Service
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: product-service
    environment: production
spec:
  project: default
  
  # Source configuration
  source:
    repoURL: https://github.com/eknathdj/devops-sample-app.git
    targetRevision: main
    path: k8s/product-service  # Path where your manifests are stored
    
    # If using Helm
    # helm:
    #   valueFiles:
    #     - values-prod.yaml
    
    # If using Kustomize
    # kustomize:
    #   namePrefix: prod-
  
  # Destination configuration
  destination:
    server: https://kubernetes.default.svc
    namespace: product-service
  
  # Sync policy
  syncPolicy:
    automated:
      prune: true      # Automatically delete resources that are no longer in Git
      selfHeal: true   # Automatically sync when cluster state doesn't match Git
      allowEmpty: false
    
    syncOptions:
      - CreateNamespace=true  # Create namespace if it doesn't exist
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Ignore differences (useful for secrets, replicas managed by HPA, etc.)
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # Ignore replicas as HPA manages this
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /spec/minReplicas
        - /spec/maxReplicas

# ---
# ArgoCD AppProject (Optional - for better organization)
# apiVersion: argoproj.io/v1alpha1
# kind: AppProject
# metadata:
#   name: product-services
#   namespace: argocd
# spec:
#   description: Product Services Project
  
#   # Allow deploying to specific namespaces
#   destinations:
#     - namespace: 'product-*'
#       server: https://kubernetes.default.svc
#     - namespace: argocd
#       server: https://kubernetes.default.svc
  
#   # Allow access to specific Git repos
#   sourceRepos:
#     - 'https://github.com/eknathdj/devops-sample-app.git'
#     - '*'  # Or restrict to specific repos
  
#   # Allow specific Kubernetes resources
#   clusterResourceWhitelist:
#     - group: ''
#       kind: Namespace
#     - group: ''
#       kind: ResourceQuota
#     - group: ''
#       kind: LimitRange
  
#   namespaceResourceWhitelist:
#     - group: '*'
#       kind: '*'
  
#   # Roles for RBAC
#   roles:
#     - name: read-only
#       description: Read-only privileges
#       policies:
#         - p, proj:product-services:read-only, applications, get, product-services/*, allow
#       groups:
#         - developers
    
#     - name: admin
#       description: Admin privileges
#       policies:
#         - p, proj:product-services:admin, applications, *, product-services/*, allow
#       groups:
#         - devops-team